version: "3"

services:
  spring:
    image: absolver/spring-toy:latest
    container_name: spring
    ports:
      - 8082:8082
    restart: unless-stopped
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    environment:
      - MYSQL_DATABASE=web
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - 3306:3306
    volumes:
      - /Users/we/config/mariadb:/docker-entrypoint-initdb.d
    restart: unless-stopped

    # nerdctl run -e MARIADB_DATABASE=web -e MARIADB_ROOT_PASSWORD=password -p 3306:3306 --name mariadb mariadb